- hosts: terraform-ansible
  tasks:
  - name: Instalando o Python3, virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes





#criando o arquivo
  #  copy:
    #  dest: /home/adminuser/index.html
     # content: <h1>Feito com terraform e ansible</h1>
  - #name: criando servidor
    #shell: "nohup busybox httpd -f -p 8080 &"
